---
# Add global settings here

# aws-cloudformation role settings
Stack.Name: proxy-resources
Stack.Template: "templates/proxy.yml.j2"

Stack.Inputs:
  VpcName: "{{ config_vpc_name }}"
  ApplicationImageId: "{{ config_application_ami }}"
  ApplicationInstanceType: "{{ config_application_instance_type }}"
  ApplicationDesiredCount: "{{ config_az_count }}"
  KeyName: "{{ config_application_keyname }}"
  ProxyImage: "{{ config_proxy_image }}"
  ProxyImageTag: "{{ config_proxy_image_tag | default('latest') }}"
  ProxyWhitelist: "{{ config_proxy_whitelist }}"